<a href="https://colab.research.google.com/github/makifcevik/pytorch-notebooks/blob/main/Pytorch_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.5.1+cu124'

In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [8]:
scalar.item()

7

In [10]:
vector = torch.tensor([2, 5])
vector

tensor([2, 5])

In [11]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [15]:
MATRIX = torch.tensor([[2, 5], [3, 6]])
MATRIX

tensor([[2, 5],
        [3, 6]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
TENSOR = torch.tensor([[[1,2], [3, 4]], [[5, 6], [7, 8]]])
TENSOR

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([2, 2, 2])

In [23]:
random_tensor = torch.rand(size=(224, 224, 3))
random_tensor.ndim, random_tensor.shape, random_tensor.dtype

(3, torch.Size([224, 224, 3]), torch.float32)

In [24]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [25]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [27]:
zero_to_ten = torch.arange(0, 11, 1)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
zeros = torch.zeros_like(input=zero_to_ten)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [30]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [31]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.7534, 0.5732, 0.1824, 0.2130],
        [0.8657, 0.1000, 0.2591, 0.2573],
        [0.4871, 0.2801, 0.8193, 0.4778]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [36]:
tensor = torch.tensor([10, 20, 30])
print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
print(tensor / 10)
print(tensor)  # Tensors don't change unless reassigned

tensor([20, 30, 40])
tensor([ 0, 10, 20])
tensor([100, 200, 300])
tensor([1., 2., 3.])
tensor([10, 20, 30])


In [37]:
tensor = torch.tensor([1, 2, 3])
tensor = tensor * 100
tensor

tensor([100, 200, 300])

In [40]:
tensor = torch.tensor([1, 2, 3])
print(torch.multiply(tensor, 100))
tensor  # Tensor is not modified

tensor([100, 200, 300])


tensor([1, 2, 3])

In [43]:
tensor = torch.tensor([1, 2, 3])
tensor = torch.multiply(tensor, 1000)
tensor

tensor([1000, 2000, 3000])

In [46]:
tensor = torch.tensor([10, 20, 50])
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([10, 20, 50]) * tensor([10, 20, 50])
Equals: tensor([ 100,  400, 2500])


In [47]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [51]:
# Element wise multipication
tensor = torch.tensor([1, 2, 3])
tensor * tensor

tensor([1, 4, 9])

In [53]:
# Matrix multipication
tensor = torch.tensor([1, 2, 3])
torch.matmul(tensor, tensor) # Because it is a vector by vector multipication, it is a dot product in this case

tensor(14)

In [50]:
tensor = torch.tensor([1, 2, 3])
torch.dot(tensor, tensor)

tensor(14)

In [56]:
tensor = torch.tensor([1, 2, 3])
tensor @ tensor  # Matrix multipication, not recommended bc it is slower

tensor(14)

In [57]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 954 µs, sys: 1.01 ms, total: 1.97 ms
Wall time: 1.87 ms


tensor(14)

In [58]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.07 ms, sys: 2 µs, total: 1.07 ms
Wall time: 1.09 ms


tensor(14)

In [59]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor)
print(tensor.T)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [62]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
torch.mm(tensor, tensor.T)  # Shortcut for matmul

tensor([[14, 32],
        [32, 77]])