<a href="https://colab.research.google.com/github/makifcevik/pytorch-notebooks/blob/main/Pytorch_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
torch.__version__

'2.6.0+cu124'

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([2, 5])
vector

tensor([2, 5])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[2, 5], [3, 6]])
MATRIX

tensor([[2, 5],
        [3, 6]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1,2], [3, 4]], [[5, 6], [7, 8]]])
TENSOR

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 2, 2])

In [ ]:
random_tensor = torch.rand(size=(224, 224, 3))
random_tensor.ndim, random_tensor.shape, random_tensor.dtype

(3, torch.Size([224, 224, 3]), torch.float32)

In [ ]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
zero_to_ten = torch.arange(0, 11, 1)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
zeros = torch.zeros_like(input=zero_to_ten)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.7534, 0.5732, 0.1824, 0.2130],
        [0.8657, 0.1000, 0.2591, 0.2573],
        [0.4871, 0.2801, 0.8193, 0.4778]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
tensor = torch.tensor([10, 20, 30])
print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
print(tensor / 10)
print(tensor)  # Tensors don't change unless reassigned

tensor([20, 30, 40])
tensor([ 0, 10, 20])
tensor([100, 200, 300])
tensor([1., 2., 3.])
tensor([10, 20, 30])


In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor = tensor * 100
tensor

tensor([100, 200, 300])

In [ ]:
tensor = torch.tensor([1, 2, 3])
print(torch.multiply(tensor, 100))
tensor  # Tensor is not modified

tensor([100, 200, 300])


tensor([1, 2, 3])

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor = torch.multiply(tensor, 1000)
tensor

tensor([1000, 2000, 3000])

In [ ]:
tensor = torch.tensor([10, 20, 50])
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([10, 20, 50]) * tensor([10, 20, 50])
Equals: tensor([ 100,  400, 2500])


In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [ ]:
# Element wise multipication
tensor = torch.tensor([1, 2, 3])
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multipication
tensor = torch.tensor([1, 2, 3])
torch.matmul(tensor, tensor) # Because it is a vector by vector multipication, it is a dot product in this case

tensor(14)

In [ ]:
tensor = torch.tensor([1, 2, 3])
torch.dot(tensor, tensor)

tensor(14)

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor @ tensor  # Matrix multipication, not recommended bc it is slower

tensor(14)

In [ ]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 954 µs, sys: 1.01 ms, total: 1.97 ms
Wall time: 1.87 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.07 ms, sys: 2 µs, total: 1.07 ms
Wall time: 1.09 ms


tensor(14)

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor)
print(tensor.T)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
torch.mm(tensor, tensor.T)  # Shortcut for matmul

tensor([[14, 32],
        [32, 77]])

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [ ]:
x = torch.arange(0, 100, 10)
print(x)
print(f"Max: {x.max()}")
print(f"Min: {x.min()}")
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Max: 90
Min: 0
Mean: 45.0
Sum: 450


In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [ ]:
tensor = torch.arange(10., 100., 10.)
print(tensor.dtype)
tensor_float16 = tensor.type(torch.float16)
print(tensor_float16)
tensor_int8 = tensor.type(torch.int8)
print(tensor_int8)

torch.float32
tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)
tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)


In [ ]:
x = torch.arange(1., 9.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [ ]:
x = torch.arange(1., 9.)
x_reshaped = x.reshape(1, 8)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [ ]:
x = torch.arange(1., 9.)
x_reshaped = x.reshape(-1, 2)  # -1 means auto calc the first dimension which is 4 in this case
x_reshaped, x_reshaped.shape

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.],
         [7., 8.]]),
 torch.Size([4, 2]))

In [ ]:
x = torch.arange(1., 9.)
z = x.view(-1, 4)  # Changing the view of a tensor only creates a new view of the same tensor.
z, z.shape

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

In [2]:
x = torch.arange(1., 9.)
z = x.view(-1, 4)
# Changing z changes x
z[:, 0] = 15
z, x

(tensor([[15.,  2.,  3.,  4.],
         [15.,  6.,  7.,  8.]]),
 tensor([15.,  2.,  3.,  4., 15.,  6.,  7.,  8.]))

In [ ]:
x = torch.arange(1., 9.)
x_stacked = torch.stack([x, x, x, x, x], dim=0)
print(x_stacked)
x_stacked = torch.stack([x, x, x, x, x], dim=1)
print(x_stacked)

tensor([[1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.]])
tensor([[1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8.]])


In [ ]:
# .squeeze() removes dimensions of size 1 from a tensor. It is useful when dealing with unnecessary extra dimensions.
# Removes all dimensions with size 1.
# You can specify a specific dimension: "tensor.squeeze(dim)" Removes only if dim has size 1.

tensor = torch.tensor([[[1], [2], [3]]])  # Shape: (1, 3, 1)
squeezed = tensor.squeeze()

print(tensor)
print(squeezed)
print(squeezed.shape)

tensor([[[1],
         [2],
         [3]]])
tensor([1, 2, 3])
torch.Size([3])


In [ ]:
tensor = torch.tensor([[[1], [2], [3]]])  # Shape: (1, 3, 1)
squeezed = tensor.squeeze(0)  # Remove dim=0 only

print(squeezed.shape)  # Output: torch.Size([3, 1])

torch.Size([3, 1])


In [ ]:
squeezed = torch.tensor([[[1], [2], [3]]]).squeeze()  # Shape: (1, 3, 1)
unsqueezed = squeezed.unsqueeze(dim=1)
print(unsqueezed)
print(unsqueezed.shape)

tensor([[1],
        [2],
        [3]])
torch.Size([3, 1])


In [3]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 225, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

#Note: Because permuting returns a view (shares the same data as the original),
# the values in the permuted tensor will be the same as the original tensor
# and if you change the values in the view, it will change the values of the original.

Previous shape: torch.Size([224, 225, 3])
New shape: torch.Size([3, 224, 225])


In [4]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [6]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}\n")
print(f"Second square bracket: {x[0][0]}\n")
print(f"Third square bracket: {x[0][0][0]}\n")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Second square bracket: tensor([1, 2, 3])

Third square bracket: 1



In [7]:
# Get all values of 0th dimension and the 0 index of 1st dimension
print(x[:, 0])
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
print(x[:, :, 1])
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(x[:, 1, 1])
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
print(x[0, 0, :]) # same as x[0][0]

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])


In [9]:
# Numpy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

# By default, NumPy arrays are created with the datatype float64
# However, many PyTorch calculations default to using float32
# To convert, you can use: tensor = torch.from_numpy(array).type(torch.float32)

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [10]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [11]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.9191, 0.7563, 0.7652, 0.4196],
        [0.9093, 0.3780, 0.4629, 0.9902],
        [0.6719, 0.2799, 0.0987, 0.3748]])

Tensor B:
tensor([[0.8123, 0.5769, 0.6576, 0.7757],
        [0.0255, 0.0289, 0.3346, 0.6185],
        [0.2809, 0.7607, 0.7351, 0.7403]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [12]:
# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [2]:
torch.cuda.is_available()

True

In [3]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

In [7]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

device = "cuda" if torch.cuda.is_available() else "cpu"
device

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

# Note: .to(device) returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU
# To overwrite tensors, reassign them: some_tensor = some_tensor.to(device)

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [9]:
# To convert a GPU tensor to numpy you'll first need to convert it into a CPU tensor

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

# The above returns a copy of the GPU tensor in CPU memory so the original tensor is still on GPU.

array([1, 2, 3])